services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ecomerce_backend

    volumes:
      - ecomerce_backend:/var/run/postgresql/ecomerce_backend:rw

    ports:
      - "3001:5432"
      - "5432:5432"

volumes:
  ecomerce_backend:
