CREATE TABLE products (
    product_id SERIAL PRIMARY KEY,
    mlb_id VARCHAR(20) NOT NULL,
    site_id VARCHAR(10),
    title VARCHAR(255),
    seller_id BIGINT,
    category_id VARCHAR(20),
    official_store_id INT,
    price NUMERIC(10, 2),
    base_price NUMERIC(10, 2),
    original_price NUMERIC(10, 2),
    currency_id VARCHAR(3),
    initial_quantity INT,
    available_quantity INT,
    sold_quantity INT,
    buying_mode VARCHAR(20),
    listing_type_id VARCHAR(20),
    start_time TIMESTAMPTZ,
    stop_time TIMESTAMPTZ,
    condition VARCHAR(20),
    permalink TEXT,
    thumbnail_id VARCHAR(50),
    thumbnail TEXT,
    international_delivery_mode VARCHAR(20),
    listing_source VARCHAR(50),
    status VARCHAR(20),
    warranty VARCHAR(50),
    catalog_product_id VARCHAR(20),
    domain_id VARCHAR(50),
    parent_item_id VARCHAR(20),
    automatic_relist BOOLEAN,
    date_created TIMESTAMPTZ,
    last_updated TIMESTAMPTZ,
    health INT,
    catalog_listing BOOLEAN
);
