DROP TABLE IF EXISTS descriptions CASCADE;
DROP TABLE IF EXISTS attributes CASCADE;
DROP TABLE IF EXISTS variations CASCADE;
DROP TABLE IF EXISTS attribute_combinations CASCADE;
DROP TABLE IF EXISTS seller_payment_methods CASCADE;
DROP TABLE IF EXISTS shipping CASCADE;
DROP TABLE IF EXISTS seller_address CASCADE;
